### ISSUE TITLE
Не удается получить значение параметра по имени датчика в шаблоне

### ISSUE THREAD

**Issue by yser1** [u236/homed-service-automation#11]
День добрый, столкнулся со следующей проблемой - не удается получить значение параметра по имени датчика в шаблоне, использовал пример из вики  " {{ property | zigbee/kitchenThermometer | temperature }} ".

пробовал разные варианты (с пробелов в имен, без пробела, английское имя):
{{ property | zigbee/Термометр Кухня | temperature }} 
{{ property | zigbee/ТермометрКухня | temperature }} 
{{ property | zigbee/TermKitchen | temperature }} 
ни один из вариантов обращения по имени не сработал. 

Когда обратился к датчику по IEEE address-у  - то все заработало.
Если это ошибка и будеш вносить исправления, было бы здорово если можно было бы обратиться к датчику вот таким образом:
{{ property | zigbee/**Термометр {{ triggerName }}**  | temperature }}

**Comment by u236** [comment]
по поводу вложенных шаблонов сегодня подумаю, пока они не работают

**Comment by u236** [comment]
немного [доработал](https://github.com/u236/homed-service-automation/commit/6439e5c4c509b9a1189d13f65939beb708428986) обработчик шаблонов, теперь вложенные шаблоны работают, бинарник в [песочнице](https://sandbox.u236.org/homed-automation/), можно пробовать
![Screenshot_2024-08-28_11-33-32](https://github.com/user-attachments/assets/8b5d2925-6514-42ab-8471-1ebe7c345520)
![Screenshot_2024-08-28_11-33-21](https://github.com/user-attachments/assets/4d3e55e5-893a-477d-a6d0-8ca41ae5bf00)

**Comment by yser1** [comment]
сейчас, ничего не меняя, активировал автоматизацию  -  все работает! не понимаю почему не работало до этого, возможно повлияла вчерашняя перезагрузка роутера с координатором.  

заменил бинарник автоматизации и попробовал "вложенные шаблоны" - все отлично работает.

спасибо!
