### ISSUE TITLE
Что не так с автоматизаций 

### ISSUE THREAD

**Issue by yser1** [u236/homed-service-automation#14]
День добрый, попробую описать проблему: 

У меня есть счетчик элекроэнергии (с ферритовым колечком)  помимо ватт, ампер и напряжения у него есть парметр "Energy" который каждые 20-30 мин. показывает сколько энергии потреблено. 

Создал устройство в разделе custom c параметром "Всего" и автоматизацией (при изменении "Energy") увеличивал его на значение "Energy" (т.е. "Всего" = "Всего" + "Energy") - все работало хорошо (и значение и график). 

Когда добавил в этоже устройство еще один параметр "Сегодня" и в ту же автоматизацию добавил  "Сегодня" = "Сегодня" + "Energy" и сброс "Сегодня" по таймеру в "00:00" - что пошло не так:
  - в дашборде иногда "Всего" и "Сегодня" показания не совпадают (например если сбрость в ноль "Всего" и "Сегодня" и понаблюдать в течении дня)
  - в графиках тоже что-то не то, особенно со вторым графиком ("Сегодня").  график должен всегда идти на повышение т.к.  значение "Energy" всегда положительное, а значения "Всего" и "Сегодня" всегда увеличиваются, а на графике есть всплески (график прикрепил).  
![Screenshot 2024-11-19 at 09-12-19 HOMEd](https://github.com/user-attachments/assets/7102ac59-9607-45ee-8d10-4639a8f69ab3)

**Comment by yser1** [comment]
Дополнение: постарался сэммитировать свою ситуацию:
  
Создал устройство Тест2 с 4-мя полями для накопления результата и поле Value с генерируемым значением  (Всего, Сегодня, Д1, Д2, Value)
Создал автоматизацию TEST-Timer которая по таймеру раз в минуту генерирует значение поля Тест2.Value
Создал автоматизацию TEST-Counters которая по изменению значения Тест2.Value увеличивает поля устройства Тест2 (Всего, Сегодня, Д1, Д2) на значение Тест2.Value
 
Перезагрузил устройство со службами homed и запустил автоматизаю TEST-Timer
 
Вот какие графики полей Всего, Сегодня, Д1 получаю (и на всех есть всплески которых не должно быть) :

![Screenshot1](https://github.com/user-attachments/assets/176d7173-485d-469b-9157-ab87e74c1cda)

Кастом устройство:
![Screenshot 2024-11-19 at 11-36-07 HOMEd](https://github.com/user-attachments/assets/5030e077-fb7d-4bd6-8152-3b181bc035e2)

Автоматизация TEST-Timer:
![Screenshot 2024-11-19 at 11-36-49 HOMEd](https://github.com/user-attachments/assets/6385dd4a-9726-42e3-883f-edc5595083f8)

Автоматизация TEST-Counters:
![Screenshot 2024-11-19 at 11-37-22 HOMEd](https://github.com/user-attachments/assets/f422c595-cdfa-4336-8b72-5e4101cd8613)

**Comment by yser1** [comment]
поймал ситуацию когда показания значений полей не совпадают:

![Screenshot 2024-11-19 at 12-01-47 HOMEd](https://github.com/user-attachments/assets/23566338-73bd-4999-b797-cf8e37e1408c)

**Comment by u236** [comment]
привет, не совсем до конца понял, но вроде понял
во-первых - кинь экспорт обоих автоматизаций, попробую воспроизвести проблему
во-вторых - приходи в [чат](https://t.me/homed_chat), иногда проще "вживую" объяснить суть, чем вот так, я минут 10 втыкал, пока понял :)

**Comment by yser1** [comment]
вот автоматизации:
[TEST-Timer.json](https://github.com/user-attachments/files/17813593/TEST-Timer.json)
[TEST-Counters.json](https://github.com/user-attachments/files/17813595/TEST-Counters.json)

в чате присутствую, мне кажется не очень удобно там писать особенно если несколькими сообщения т.к. можно потерять нить темы :) 
если там напишеш, то я отвечу, в телегу наверное раз в полчаса-то точно заглядываю и почитываю

**Comment by u236** [comment]
запустил на тест (с той лишь разницей, что переименовал свойства с русского языка на английский), понаблюдаю пока, а что касается чата - ты хоть назовись, вас там почти 1000 человек уже :)

**Comment by yser1** [comment]
после обновления mqtt сервера проблема решилась
