### ISSUE TITLE
Добавить условия выполнения для mqtt trigger

### ISSUE THREAD

**Issue by NickNeoOne** [u236/homed-service-automation#4]
Добавить условия выполнения для mqtt trigger, чтобы можно было создавать триггер если числовое значение полученное из топика mqtt выше/ниже заданного значения или находится в заданном(вне заданного) диапазона.

например есть датчик качества воздуха, который шлет данные ppm в топик esp-co2_1/co2/PPM в виде числа и необходимо, чтобы при превышении значения(например при значении выше 1000), срабатывало zigbee устройство (отрывающее окно).

**Comment by u236** [comment]
https://github.com/u236/homed-service-web/commit/40713807293f26bad96b3c3d0d5b1b24d978f006

**Comment by u236** [comment]
https://github.com/u236/homed-service-automation/commit/7d34a085d171a49c91e54c11b62c8bdebc376082 + https://github.com/u236/homed-service-web/commit/40713807293f26bad96b3c3d0d5b1b24d978f006
