### ISSUE TITLE
 Добавить условия (Conditions) sunset и sunrise

### ISSUE THREAD

**Issue by DGMiron** [u236/homed-service-automation#5]
Прошу добавить sunset и sunrise как условия (Conditions). Было бы удобно для некоторых автоматизаций, запускающихся другим триггером, но при условии "от заката до рассвета" (например: вкл света на заднем дворе при открывании двери в темное время суток). Условием time тоже можно, но лень редактировать 4-6 раз в год ))

**Comment by u236** [comment]
https://github.com/u236/homed-service-automation/commit/0a2581aef5e60aaaaa5bc3e89a11d53a043c53de
