### ISSUE TITLE
Добавить возможность копировать\дублировать написанную автоматизацию в web интерфейсе

### ISSUE THREAD

**Issue by Crazy-Child** [u236/homed-service-automation#6]
Добавить возможность копировать\дублировать написанную автоматизацию в web интерфейсе. Так упростит написание однотипных, схожих автоматизаций для устройств.

**Comment by u236** [comment]
https://github.com/u236/homed-service-web/commit/ae8c83dcf5b5b403e6476e584a60510f9c5d04f5
